export const DAILY_QUOTES = [
  'The stars align in your favor today.',
  'Magic flows through every moment.',
  'Your intuition is your greatest guide.',
  'Embrace the mystery of the universe.',
  'Today brings unexpected blessings.',
  'Trust in the journey ahead.',
  'Your energy attracts positive change.',
  'The moon whispers secrets of wisdom.',
  'Every step forward is guided by fate.',
  'Your aura shines with inner light.',
  'Ancient wisdom flows through your veins.',
  'The cosmos celebrates your presence.',
  'Your dreams are messages from the universe.',
  'Today&apos;s energy supports your growth.',
  'Magic surrounds those who believe.',
  'Your spirit is connected to all things.',
  'The universe conspires in your favor.',
  'Wisdom comes from listening to your heart.',
  'Your path is illuminated by starlight.',
  'Embrace the magic within you.',
];
